package com.replay.product;

public enum ConsoleType {
    NES, SNES, NINTENDO_64, GAMECUBE, WII, WII_U, SWITCH,
    GAMEBOY, GAMEBOY_COLOR, GAMEBOY_ADVANCE, NINTENDO_DS, NINTENDO_3DS,
    PLAYSTATION, PS2, PS3, PS4, PS5,
    XBOX, XBOX_360, XBOX_ONE, XBOX_SERIES,
    SEGA_MEGA_DRIVE, SEGA_SATURN, SEGA_DREAMCAST,
    NEC_PC_ENGINE, ATARI, AUTRE
}
